spring.application.name=sentiment-analysis-be

# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

# Spring AI configuration
spring.ai.openai.api-key={OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini